### PR TITLE
[WPF] Fixed an exception when selecting multiple TreeView items

### LINKED ISSUE #740: WPF, TreeView: ArgumentOutOfRangeException when selecting multiple elements
Repro steps:

1. In sample xwt apps, modify "TreeView" sample so that it allows multiple selection:
```C#
public TreeViews ()
{
	...
	view.SelectionMode = SelectionMode.Multiple;
	...
}
```
2. Launch `WpfTest` project
3. Open `Widgets/TreeView` sample
4. Click "Add"
5. Shift-click any item except the selected one

Expected result:
The items between the selected and clicked are selected

Actual result:
`System.ArgumentOutOfRangeException`

### PR DESCRIPTION
**Pull request by alsorokin**
This fixes #740 

Just don't forget to fill up `shiftStart` when selected items are changed. Also, check for null.

### CODE REVIEW

File: TestApps/Samples/Samples/TreeViews.cs [hunk 1]
```diff
@@ -43,6 +43,7 @@ public TreeViews ()
 			TreeView view = new TreeView ();
 			TreeStore store = new TreeStore (triState, check, option1, option2, option3, text, desc);
 			view.GridLinesVisible = GridLines.Both;
+			view.SelectionMode = SelectionMode.Multiple;
```
Comment (slluis) [inline TestApps/Samples/Samples/TreeViews.cs]: Can you revert this change?

**Comment by slluis** [comment]
The fix looks good.

**Comment by alsorokin** [comment]
@slluis I've reverted the change in the sample, as you asked.
